# 
# - - - - - - - - - - - - - - - - - - - -
default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: HogHead

development:
  <<: *default
  database: jem_note_dev

test: &test
  <<: *default
  database: jem_note_tst

production:
  <<: *default
  database: jem_note

cucumber:
  <<: *test

# - - - - - - - - - - - - - - - - - - - -
