# 
# - - - - - - - - - - - - - - - - - - - -
default: &default
  adapter: postgresql
  host: localhost
  username: rails
  password: xx

development:
  <<: *default
  database: jem_note_dev

test: &test
  <<: *default
  database: jem_note_tst

production:
  <<: *default
  database: jem_note

cucumber:
  <<: *test

# - - - - - - - - - - - - - - - - - - - -
# - Issue with unix socket dirs
# - Fixed by citing host:localhost
# - - - - - - - - - - - - - - - - - - - -
